# Generated by Django 4.2.13 on 2026-06-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yatranepal.gis_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('nepali', 'Nepali Traveler'), ('foreign', 'Foreign Tourist')], max_length=20)),
                ('home_city', models.CharField(max_length=100)),
                ('home_location', yatranepal.gis_fields.PointField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
