# Generated by Django 4.2.13 on 2026-06-19 18:43

from django.db import migrations, models
import django.db.models.deletion
import yatranepal.gis_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BipadIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bipad_id', models.IntegerField(unique=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', yatranepal.gis_fields.PointField(blank=True, null=True)),
                ('incident_date', models.DateField()),
                ('severity', models.CharField(max_length=50)),
                ('deaths', models.IntegerField(default=0)),
                ('injured', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisasterRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('landslide', 'Landslide'), ('flood', 'Flash Flood'), ('earthquake', 'Earthquake'), ('storm', 'Thunderstorm'), ('river_overflow', 'River Overflow'), ('road_closure', 'Road Closure')], max_length=30)),
                ('probability_percent', models.IntegerField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('month', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_risks', to='trips.destination')),
            ],
        ),
    ]
