# Generated by Django 4.2.13 on 2026-06-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_max_c', models.FloatField()),
                ('temp_min_c', models.FloatField()),
                ('precipitation_probability', models.IntegerField()),
                ('weather_code', models.IntegerField()),
                ('wind_speed_kmh', models.FloatField()),
                ('is_sailing_suitable', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='trips.destination')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('destination', 'forecast_date')},
            },
        ),
    ]
