# Generated by Django 4.2.13 on 2026-06-19 18:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import yatranepal.gis_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('destination_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('activity_type', models.CharField(choices=[('sailing', 'Sailing'), ('trekking', 'Trekking'), ('rafting', 'Rafting'), ('paragliding', 'Paragliding'), ('safari', 'Safari'), ('diving', 'Diving')], max_length=20)),
                ('location', yatranepal.gis_fields.PointField()),
                ('altitude_m', models.IntegerField(default=0)),
                ('distance_from_ktm_km', models.IntegerField()),
                ('permit_required', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('best_season_months', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LandslideZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('highway', models.CharField(max_length=100)),
                ('zone_polygon', yatranepal.gis_fields.PolygonField()),
                ('risk_level', models.CharField(choices=[('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('active_months', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_location', yatranepal.gis_fields.PointField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('travel_rating', models.FloatField(blank=True, null=True)),
                ('route_geom', yatranepal.gis_fields.LineStringField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_score', models.FloatField()),
                ('route_safety_score', models.FloatField()),
                ('activity_fit_score', models.FloatField()),
                ('infrastructure_score', models.FloatField()),
                ('crowd_level_score', models.FloatField()),
                ('disaster_risk_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('recommendation', models.TextField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='trips.trip')),
            ],
        ),
    ]
